using Content.Client.UserInterface.Controls;
using Content.Shared._BRatbite.Arcade;
using Content.Shared.Random.Helpers;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client._BRatbite.Arcade;

[GenerateTypedNameReferences]
public sealed partial class MineSweeperWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    public Action<int, int, bool>? OnCellClicked;
    public Action? OnRestartClicked;
    private Dictionary<MineSweeperBlockState, List<Texture>> _cells = new();
    private readonly SpriteSystem _sprite;

    public MineSweeperWindow()
    {
        RobustXamlLoader.Load(this);
        _sprite = _entManager.System<SpriteSystem>();
        ReloadPrototypes();
        RestartButton.OnPressed += (_) => OnRestartClicked?.Invoke();
    }

    public void ReloadPrototypes()
    {
        _cells.Clear();
        foreach (var cellProto in _proto.EnumeratePrototypes<MineSweeperCellPrototype>())
        {
            var texture = _sprite.Frame0(cellProto.Icon);
            if (_cells.TryGetValue(cellProto.State, out var list))
                list.Add(texture);
            else
                _cells.Add(cellProto.State, new() { texture });
        }
    }

    public void UpdateBoard(MineSweeperBUIState state)
    {
        var gameEnded = state.State == MineSweeperGameState.Lost || state.State == MineSweeperGameState.Won;
        GameStateContainer.Visible = gameEnded;
        GameStateLabel.Text = state.State switch
        {
            MineSweeperGameState.Won => Loc.GetString("mine-sweeper-win-text"),
            MineSweeperGameState.Lost => Loc.GetString("mine-sweeper-loss-text"),
            _ => "",
        };
        Board.RemoveAllChildren();
        var (w, h) = (state.BoardWidth, state.BoardHeight);
        Board.Columns = w;

        for (var i = 0; i < state.Board.Count; i++)
        {
            var _random = new Random(SharedRandomExtensions.HashCodeCombine((int) state.CreationTime.TotalSeconds, i));
            var (x, y) = (i % w, i / w);
            var cell = state.Board[x + y * w];
            if (!_cells.TryGetValue(cell, out var textures)) continue;//throw new ArgumentOutOfRangeException("Invalid cell state");
            var texture = _random.Pick(textures);
            var textureButton = new TextureButton()
            {
                TextureNormal = texture,
                Scale = new(1, 1),
                EnableAllKeybinds = true,
            };
            var (_x, _y) = (x, y);
            if (!gameEnded)
            {
                textureButton.OnPressed += (args) =>
                {
                    var pressed = args.Event.Function;
                    bool isFlag;
                    if (pressed == EngineKeyFunctions.UIClick)
                        isFlag = false;
                    else if (pressed == EngineKeyFunctions.UIRightClick)
                        isFlag = true;
                    else
                        return;
                    OnCellClicked?.Invoke(x, y, isFlag);
                };
            }
            Board.AddChild(textureButton);
        }
    }
}
