using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Temperature;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._BRatbite.Atmos;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._BRatbite.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasMinerComputerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly SpriteSystem _sprite;
    private NetEntity? _selectedMinerId = null;
    private GasMinerState[] _miners = [];

    public GasMinerComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();

        Miners.OnItemSelected += args =>
        {
            if (Miners[args.ItemIndex].Metadata is not NetEntity id)
                return;
            _selectedMinerId = id;
            UpdateMinerData();
        };
        Miners.OnItemDeselected += _ =>
        {
            _selectedMinerId = null;
            UpdateMinerData();
        };
    }

    public void Populate(GasMinerComputerBoundUserInterfaceState state)
    {
        _miners = state.Miners;
        BalanceLabel.Text = state.Balance.ToString();
        Miners.Clear();
        foreach (var gasMiner in state.Miners)
        {
            var item = Miners.AddItem(gasMiner.Name, _sprite.Frame0(new SpriteSpecifier.Rsi(new ResPath("/Textures/Structures/Piping/Atmospherics/miners.rsi"), "miner")), metadata: gasMiner.NetworkId);
            item.Selected = gasMiner.NetworkId == _selectedMinerId;
        }
    }

    private void UpdateMinerData()
    {
        var miner = _miners.FirstOrDefault(m => m.NetworkId == _selectedMinerId);
        RightContainer.Visible = miner == null;
        if (miner is null) return;
        SelectedMinerName.Text = miner.Name;
        AvailableMoles.Text = miner.AvailableMoles.ToString();
        SellPriceLabel.Text = miner.SellPrice.ToString();
        BuyPriceLabel.Text = miner.BuyPrice.ToString();
        StopButton.Pressed = miner.State == GasMinerSellingState.None;
        SellButton.Pressed = miner.State == GasMinerSellingState.Sell;
        BuyButton.Pressed = miner.State == GasMinerSellingState.Buy;
        ExchangeRateInput.Value = miner.ExchangeRatePerSecond;
    }
}
