using Content.Client.UserInterface.Controls;
using Robust.Client.GameObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._BRatbite.Atmos;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._BRatbite.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasMinerComputerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly SpriteSystem _sprite;
    private NetEntity? _selectedMinerId = null;
    private GasMinerUIState[] _miners = [];
    private float _exchangeValue;
    private GasMinerSellingState _gasState;
    public Action<(NetEntity entity, float exchangeValue, GasMinerSellingState state)>? OnMessageSend;

    public GasMinerComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();

        Miners.OnItemSelected += args =>
        {
            if (Miners[args.ItemIndex].Metadata is not NetEntity id)
                return;
            _selectedMinerId = id;
            UpdateMinerData();
        };
        ExchangeRateInput.OnValueChanged += args =>
        {
            _exchangeValue = args.Value;
            CreateAndSendMessage();
        };

        BuyButton.OnPressed += _ =>
        {
            _gasState = GasMinerSellingState.Buy;
            CreateAndSendMessage();
        };
        SellButton.OnPressed += _ =>
        {
            _gasState = GasMinerSellingState.Sell;
            CreateAndSendMessage();
        };
        StopButton.OnPressed += _ =>
        {
            _gasState = GasMinerSellingState.None;
            CreateAndSendMessage();
        };
    }

    public void Populate(GasMinerComputerBoundUserInterfaceState state)
    {
        _miners = state.Miners;
        BalanceLabel.Text = state.Balance.ToString();
        Miners.Clear();
        foreach (var gasMiner in state.Miners)
        {
            var item = Miners.AddItem(gasMiner.Name, _sprite.Frame0(new SpriteSpecifier.Rsi(new ResPath("/Textures/Structures/Piping/Atmospherics/miners.rsi"), "miner")), metadata: gasMiner.NetworkId);
            item.Selected = gasMiner.NetworkId == _selectedMinerId;
        }
    }

    private void UpdateMinerData()
    {
        var miner = _miners.FirstOrDefault(m => m.NetworkId == _selectedMinerId);
        RightContainer.Visible = miner != null;
        if (miner is null) return;
        SelectedMinerName.Text = miner.Name;
        AvailableMoles.Text = miner.AvailableMoles.ToString();
        SellPriceLabel.Text = miner.SellPrice.ToString();
        BuyPriceLabel.Text = miner.BuyPrice.ToString();
        StopButton.Pressed = miner.State == GasMinerSellingState.None;
        SellButton.Pressed = miner.State == GasMinerSellingState.Sell;
        BuyButton.Pressed = miner.State == GasMinerSellingState.Buy;
        ExchangeRateInput.Value = miner.ExchangeRatePerSecond;
        _exchangeValue = miner.ExchangeRatePerSecond;
        _gasState = miner.State;
    }

    private void CreateAndSendMessage()
    {
        if (_selectedMinerId is null) return;
        OnMessageSend?.Invoke((_selectedMinerId.Value, _exchangeValue, _gasState));
    }
}
