using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._BRatbite.Atmos;

namespace Content.Client._BRatbite.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasMiner : Container
{
    public GasMiner()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(GasMinerUIState state)
    {
        var label = new Label();
        label.Text = state.Name;
        AddChild(label);
    }
}
