using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._BRatbite.GunTracking;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._BRatbite.GunTracking;

[GenerateTypedNameReferences]
public sealed partial class GunTrackingWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;
    private Texture? _blipTexture;
    public GunTrackingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entManager.System<SpriteSystem>();
        _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
    }

    public void SetMap(EntityUid? mapUid)
    {
        if (_entManager.TryGetComponent<TransformComponent>(mapUid, out var xform))
            NavMap.MapUid = xform.GridUid;
        else
            NavMap.Visible = false;
        NavMap.ForceNavMapUpdate();
    }

    public void PopulateGuns(List<GunStatus> guns)
    {
        if (_blipTexture is null) return;
        NavMap.TrackedEntities.Clear();
        foreach (var gun in guns)
        {
            NavMap.TrackedEntities.Add(gun.Uid, new (_entManager.GetCoordinates(gun.Coordinates), _blipTexture, Color.Red, false));
        }
    }
}
