using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Ratbite.Shared.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;

namespace Content.Ratbite.Client.Bank.Ui;

[GenerateTypedNameReferences]
public sealed partial class FranchiseTerminalWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action<string>? OnFranchiseSelected;
    public event Action<NetUserId, int>? OnWorkerPaySet;
    public event Action<NetUserId>? OnWorkerFired;
    public event Action<string, string>? OnAccountConfigured;

    private ProtoId<FranchisePrototype>? _pendingSelectionId;

    public FranchiseTerminalWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EstablishFranchiseButton.OnPressed += _ =>
        {
            if (_pendingSelectionId != null)
                OnFranchiseSelected?.Invoke(_pendingSelectionId);
        };

        UpdateAccountButton.OnPressed += _ =>
            OnAccountConfigured?.Invoke(CompanyAccountInput.Text, CompanyPasswordInput.Text);
    }

    public void PopulateSelectionScreen(List<ProtoId<FranchisePrototype>> availableProtos)
    {
        FranchiseSelectionContainer.DisposeAllChildren();
        _pendingSelectionId = null;
        EstablishFranchiseButton.Disabled = true;

        foreach (var id in availableProtos)
        {
            var btn = new Button
            {
                Text = id,
                ToggleMode = true,
                HorizontalExpand = true,
                MinSize = new Vector2(0, 32)
            };

            btn.OnPressed += _ =>
            {
                // Enforce single-toggle selection grouping rules manually
                foreach (var child in FranchiseSelectionContainer.Children)
                {
                    if (child is Button otherBtn && otherBtn != btn)
                        otherBtn.Pressed = false;
                }

                _pendingSelectionId = null;
                if (btn.Pressed)
                    _pendingSelectionId = id;

                EstablishFranchiseButton.Disabled = _pendingSelectionId == null;
            };

            FranchiseSelectionContainer.AddChild(btn);
        }
    }

    public void UpdateDashboard(ProtoId<FranchisePrototype> franchiseId, List<FranchiseTerminalWorkerData> workers, string account, int balance)
    {
        SelectionScreen.Visible = false;
        DashboardScreen.Visible = true;

        AccountLabel.Text = string.IsNullOrEmpty(account) ? "UNLINKED ACCOUNT" : account;
        BalanceLabel.Text = balance.ToString("N0");

        var proto = _proto.Index(franchiseId);

        ObjectiveHeaderLabel.Text = $"{proto.ID.ToUpper()} DIRECTIVES";

        RenderWorkersList(workers);
        RenderObjectives(proto);
    }

    private void RenderWorkersList(List<FranchiseTerminalWorkerData> workers)
    {
        WorkersListContainer.DisposeAllChildren();

        if (workers.Count == 0)
        {
            WorkersListContainer.AddChild(new Label { Text = "No registered sub-franchise personnel.", FontColorOverride = Color.DarkGray, Margin = new Thickness(4) });
            return;
        }

        foreach (var worker in workers)
        {
            var card = new PanelContainer { StyleClasses = { "PanelDark" }, Margin = new Thickness(2) };
            var content = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(6), SeparationOverride = 4 };

            content.AddChild(new Label { Text = worker.Name, StyleClasses = { "LabelSubText" } });

            var payRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
            payRow.AddChild(new Label { Text = "Wage:", FontColorOverride = Color.LightGray });

            var payInput = new LineEdit { Text = worker.PayRate.ToString(), MinSize = new Vector2(60, 24) };
            payInput.IsValid += text => int.TryParse(text, out var val) && val >= 0;
            payInput.OnTextEntered += args =>
            {
                if (int.TryParse(args.Text, out var rate))
                    OnWorkerPaySet?.Invoke(worker.UserId, rate);
            };
            payRow.AddChild(payInput);

            var space = new Control { HorizontalExpand = true };
            payRow.AddChild(space);

            var fireBtn = new Button { Text = "FIRE", StyleClasses = { "Caution" }, MinSize = new Vector2(50, 24) };
            fireBtn.OnPressed += _ => OnWorkerFired?.Invoke(worker.UserId);
            payRow.AddChild(fireBtn);

            content.AddChild(payRow);
            card.AddChild(content);
            WorkersListContainer.AddChild(card);
        }
    }

    private void RenderObjectives(FranchisePrototype proto)
    {
        ObjectivesListContainer.DisposeAllChildren();

        // 1. Basic operations listing layout injection loop
        if (proto.BasicObjectives.Count > 0)
        {
            ObjectivesListContainer.AddChild(new Label { Text = "Standard Operations", FontColorOverride = Color.LightGray });
            foreach (var obj in proto.BasicObjectives)
            {
                ObjectivesListContainer.AddChild(CreateObjectiveBlock(obj.Id, Color.DarkGray));
            }
        }

        // 2. Special operations high-risk directive elements
        if (proto.SpecialObjectives.Count > 0)
        {
            ObjectivesListContainer.AddChild(new Label { Text = "High-Risk Strategy Targets", FontColorOverride = Color.Red });
            foreach (var obj in proto.SpecialObjectives)
            {
                ObjectivesListContainer.AddChild(CreateObjectiveBlock(obj.Id, Color.FromHex("#3A1A1A")));
            }
        }
    }

    private PanelContainer CreateObjectiveBlock(string text, Color backColor)
    {
        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = backColor },
            Margin = new Thickness(2),
            Children = {
                new Label { Text = text, Margin = new Thickness(6) }
            }
        };
    }
}
