using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Ratbite.Client.Bank.Ui;

[GenerateTypedNameReferences]
public sealed partial class PaykeyWindow : FancyWindow
{
    public event Action<string, string, int, int>? OnAmountConfirmed;

    public PaykeyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AmountInput.IsValid += text => int.TryParse(text, out var val) && val >= 0;
        BankDropdown.OnItemSelected += args => BankDropdown.SelectId(args.Id);
        SendMoney.OnPressed += _ => Submit();
    }

    /// <summary>
    /// Populates the drop-down box options sent down from the BUI layer.
    /// </summary>
    public void UpdateAvailableBanks(List<NetEntity> bankIds)
    {
        BankDropdown.Clear();

        if (bankIds.Count == 0)
        {
            BankDropdown.AddItem("No Banks Connected");
            BankDropdown.Disabled = true;
            return;
        }

        BankDropdown.Disabled = false;
        foreach (var id in bankIds)
        {
            BankDropdown.AddItem($"Bank Terminal: {id}");
        }
    }

    private void Submit()
    {
        if (!int.TryParse(AmountInput.Text, out var amount))
        {
            AmountInput.Text = string.Empty;
            return;
        }

        if (amount < 5 || amount > 100000)
        {
            AmountInput.Text = string.Empty;
            return;
        }

        OnAmountConfirmed?.Invoke(AccountInput.Text, PasswordInput.Text, BankDropdown.SelectedId, amount);
        Close();
    }
}
