# SPDX-License-Identifier: AGPL-3.0-or-later

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  #- Amber kil by upstream we still have ours but it testfails oh well.
  - Bagel
#  - Box - Ratbite - not supported
  - Cluster
  #- Core
  #- Loop Goobstation - I love maintenance!!!
  - Marathon
#  - Meta
 # - Oasis
  - Omega
#  - Origin - Ratbite - not supported
  - Saltern
  - Packed
  #- Train # Goobstation - all my friends hate train
  #- FlandHighPop # Ratbite - Unmaintained
  - OasisHighPop
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  #- Plasma # Goob - No. Leave it to the mappers.
  #- Reach
  #- Exo # Goobstation - Just no
  - Snowball
