// SPDX-FileCopyrightText: 2026 Mond-Mann <moonmanrreal@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.Mining.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Mining.UI;

[GenerateTypedNameReferences]
public sealed partial class OreScannerConsoleWindow : FancyWindow
{
    public OreScannerConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        
        RecenterButton.OnPressed += _ => OreDisplay.ResetView();
    }

    public void UpdateState(OreScannerInterfaceState state)
    {
        OreDisplay.UpdateState(state);
    }
}
