- type: entity
  parent: ClothingOuterBase
  id: ClothingOuterSuitTramDriver
  name: tram driver suit
  description: It protects from everything that could distract you. That is, nothing at all.
  components:
  - type: Sprite
    sprite: _BRatBites/Clothing/OuterClothing/Coats/tramdriver.rsi
  - type: Clothing
    sprite: _BRatBites/Clothing/OuterClothing/Coats/tramdriver.rsi