- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadHatTramDriver
  name: tram driver hat
  description: It smells like confidence.
  components:
  - type: Sprite
    sprite: _BRatBites/Clothing/Head/Hats/tramdriver.rsi
  - type: Clothing
    sprite: _BRatBites/Clothing/Head/Hats/tramdriver.rsi
  - type: Tag
    tags:
    - ClothMade
    - Recyclable
    - WhitelistChameleon