using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Ratbite.Client.Lobby.Ui;

[GenerateTypedNameReferences]
public sealed partial class LobbyCreditPanel : BoxContainer
{
    public event Action<int>? OnBringAmountChanged;

    private int _maxBalance = 0;
    private int _currentBringAmount = 0;

    public LobbyCreditPanel()
    {
        RobustXamlLoader.Load(this);

        BringAmountInput.IsValid += text => int.TryParse(text, out var val) && val >= 0;

        PlusButton.OnPressed += _ => AdjustAmount(50);
        MinusButton.OnPressed += _ => AdjustAmount(-50);
        BringAmountInput.OnTextEntered += args => SetAmount(args.Text);
    }

    public void SetWalletState(int totalOocBalance, int currentBringAmount)
    {
        _maxBalance = totalOocBalance;
        _currentBringAmount = Math.Clamp(currentBringAmount, 0, _maxBalance);

        OOCBalanceLabel.Text = _maxBalance.ToString();
        BringAmountInput.Text = _currentBringAmount.ToString();
    }

    private void AdjustAmount(int delta)
    {
        int target = _currentBringAmount + delta;
        UpdateAndNotify(Math.Clamp(target, 0, _maxBalance));
    }

    private void SetAmount(string text)
    {
        if (int.TryParse(text, out var value))
        {
            UpdateAndNotify(Math.Clamp(value, 0, _maxBalance));
        }
    }

    private void UpdateAndNotify(int amount)
    {
        if (_currentBringAmount == amount) return;

        _currentBringAmount = amount;
        BringAmountInput.Text = _currentBringAmount.ToString();
        OnBringAmountChanged?.Invoke(_currentBringAmount);
    }
}
