// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;

        // CCVar.
        private int _maxNameLength;
        private int _maxIdJobLength;

        private AccessLevelControl _accessButtons = new();
        private readonly List<string> _jobPrototypeIds = new();

        private string? _lastFullName;
        private string? _lastJobTitle;
        private string? _lastJobProto;

        // Ratbite start
        private Color InactiveModulation = Color.White;
        private Color ActiveModulation = Color.LightGreen;
        private Color EmergencyAddedModulation = Color.LightBlue;
        private Color EmergencyRemovedModulation = Color.Orange;
        // Ratbite end

        // The job that will be picked if the ID doesn't have a job on the station.
        private static ProtoId<JobPrototype> _defaultJob = "Passenger";

        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner, IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

            FullNameLineEdit.OnTextEntered += _ => SubmitData();
            FullNameLineEdit.IsValid = s => s.Length <= _maxNameLength;
            FullNameLineEdit.OnTextChanged += _ =>
            {
                FullNameSaveButton.Disabled = FullNameSaveButton.Text == _lastFullName;
            };
            FullNameSaveButton.OnPressed += _ => SubmitData();

            JobTitleLineEdit.OnTextEntered += _ => SubmitData();
            JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;
            JobTitleLineEdit.OnTextChanged += _ =>
            {
                JobTitleSaveButton.Disabled = JobTitleLineEdit.Text == _lastJobTitle;
            };
            JobTitleSaveButton.OnPressed += _ => SubmitData();
            // Goobstation Start
            SearchLineEdit.OnTextChanged += args =>
            {
                var query = args.Text.Trim();
                var containerChild = AccessLevelControlContainer.GetChild(0);
                containerChild.RemoveAllChildren();

                if (string.IsNullOrEmpty(query))
                {
                    foreach (var button in _accessButtons.ButtonsList.Values)
                        containerChild.AddChild(button);
                    return;
                }

                foreach (var (id, button) in _accessButtons.ButtonsList)
                    if (id.Id.Contains(query, StringComparison.CurrentCultureIgnoreCase))
                        containerChild.AddChild(button);
            };
            // Goobstation End

            var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().ToList();
            jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));

            foreach (var job in jobs)
            {
                if (!job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                {
                    continue;
                }

                _jobPrototypeIds.Add(job.ID);
                JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobPrototypeIds.Count - 1);
            }

            SelectAllButton.OnPressed += _ =>
            {
                SetAllAccess(true);
                SubmitData();
            };

            DeselectAllButton.OnPressed += _ =>
            {
                SetAllAccess(false);
                SubmitData();
            };

            JobPresetOptionButton.OnItemSelected += SelectJobPreset;
            _accessButtons.Populate(accessLevels, prototypeManager, false, true);
            // Ratbite start
            foreach (var (_, button) in _accessButtons.ButtonsList)
            {
                button.OnPressed += (args) =>
                {
                    if (args.Event.Function == EngineKeyFunctions.UIClick)
                    {
                        button.Modulate = button.Modulate == ActiveModulation ? InactiveModulation : ActiveModulation;
                    }
                    else if (args.Event.Function == EngineKeyFunctions.UIRightClick)
                    {
                        button.Modulate = button.Modulate == EmergencyAddedModulation ? EmergencyRemovedModulation : EmergencyAddedModulation;
                    }
                };
            }
            // Ratbite end

            AccessLevelControlContainer.AddChild(_accessButtons);

            foreach (var (id, button) in _accessButtons.ButtonsList)
            {
                button.OnPressed += _ => SubmitData();
            }
        }

        /// <param name="enabled">If true, every individual access button will be pressed. If false, each will be depressed.</param>
        private void SetAllAccess(bool enabled)
        {
            foreach (var button in _accessButtons.ButtonsList.Values)
            {
                button.Modulate = enabled ? ActiveModulation : InactiveModulation;
            }
        }

        private void SelectJobPreset(OptionButton.ItemSelectedEventArgs args)
        {
            if (!_prototypeManager.TryIndex(_jobPrototypeIds[args.Id], out JobPrototype? job))
            {
                return;
            }

            JobTitleLineEdit.Text = Loc.GetString(job.Name);
            args.Button.SelectId(args.Id);

            SetAllAccess(false);
            var setCorrectAccess = (IReadOnlyCollection<ProtoId<AccessLevelPrototype>> accessList, IReadOnlyCollection<ProtoId<AccessGroupPrototype>>? groupList, Color modulation) =>
                {
                    // this is a sussy way to do this
                    foreach (var access in accessList)
                    {
                        if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                        {
                            button.Modulate = modulation;
                        }
                    }

                    foreach (var group in groupList ?? [])
                    {
                        if (!_prototypeManager.TryIndex(group, out AccessGroupPrototype? groupPrototype))
                        {
                            continue;
                        }

                        foreach (var access in groupPrototype.Tags)
                        {
                            if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                            {
                                button.Modulate = modulation;
                            }
                        }
                    }
                };
            setCorrectAccess(job.Access, job.AccessGroups, ActiveModulation);
            setCorrectAccess(job.EmergencyAccessAdded, null, EmergencyAddedModulation);
            setCorrectAccess(job.EmergencyAccessRemoved, null, EmergencyRemovedModulation);



            SubmitData();
        }

        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.PrivilegedIdName;

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            TargetIdLabel.Text = state.TargetIdName;

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent;

            var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.TargetIdFullName;
            var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != state.TargetIdJobTitle;

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            FullNameLineEdit.Editable = interfaceEnabled;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }

            FullNameSaveButton.Disabled = !interfaceEnabled || !fullNameDirty;

            JobTitleLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            JobTitleLineEdit.Editable = interfaceEnabled;
            if (!jobTitleDirty)
            {
                JobTitleLineEdit.Text = state.TargetIdJobTitle ?? string.Empty;
            }

            JobTitleSaveButton.Disabled = !interfaceEnabled || !jobTitleDirty;

            JobPresetOptionButton.Disabled = !interfaceEnabled;

            // Ratbite start
            foreach (var (accessName, button) in _accessButtons.ButtonsList)
            {
                button.Disabled = !(state.AllowedModifyAccessList?.Contains(accessName)) ?? true;
                button.Modulate = InactiveModulation;
                if (state.TargetIdAccessList?.Contains(accessName) ?? false)
                {
                    button.Modulate = ActiveModulation;
                }

                if (state.EmergencyAddedAccessList?.Contains(accessName) ?? false)
                {
                    button.Modulate = EmergencyAddedModulation;
                }

                if (state.EmergencyRemovedAccessList?.Contains(accessName) ?? false)
                {
                    button.Modulate = EmergencyRemovedModulation;
                }
            }
            // Ratbite end
            // _accessButtons.UpdateState(state.TargetIdAccessList?.ToList() ??
            //                            new List<ProtoId<AccessLevelPrototype>>(),
            //                            state.AllowedModifyAccessList?.ToList() ??
            //                            new List<ProtoId<AccessLevelPrototype>>());

            var jobIndex = _jobPrototypeIds.IndexOf(state.TargetIdJobPrototype);
            // If the job index is < 0 that means they don't have a job registered in the station records
            // or the IdCardComponent's JobPrototype field.
            // For example, a new ID from a box would have no job index.
            if (jobIndex < 0)
            {
                jobIndex = _jobPrototypeIds.IndexOf(_defaultJob);
            }

            JobPresetOptionButton.SelectId(jobIndex);

            _lastFullName = state.TargetIdFullName;
            _lastJobTitle = state.TargetIdJobTitle;
            _lastJobProto = state.TargetIdJobPrototype;
        }

        private void SubmitData()
        {
            // Don't send this if it isn't dirty.
            var jobProtoDirty = _lastJobProto != null &&
                                _jobPrototypeIds[JobPresetOptionButton.SelectedId] != _lastJobProto;

            // Ratbite edit: emergency access
            // all access including emergency ones
            var allAccess = _accessButtons.ButtonsList.Where(x => x.Value.Modulate != InactiveModulation);
            var regularAccess = allAccess.Where(x => x.Value.Modulate == ActiveModulation || x.Value.Modulate == EmergencyRemovedModulation);
            var emergencyAddedAccess = allAccess.Where(x => x.Value.Modulate == EmergencyAddedModulation);
            var emergencyRemovedAccess = allAccess.Where(x => x.Value.Modulate == EmergencyRemovedModulation);
            _owner.SubmitData(
                FullNameLineEdit.Text,
                JobTitleLineEdit.Text,
                // Iterate over the buttons dictionary, filter by `Modulate`, only get key from the key/value pair
                regularAccess.Select(x => x.Key).ToList(),
                jobProtoDirty ? _jobPrototypeIds[JobPresetOptionButton.SelectedId] : string.Empty,
                emergencyAddedAccess.Select(x => x.Key).ToList(),
                emergencyRemovedAccess.Select(x => x.Key).ToList()
            );
        }
    }
}
