- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  whitelisted: true
  startingGear: PrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  canBeAntag: false
  special: #mald perma prisoner change
  - !type:AddComponentSpecial 
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
      catchingFailDamage:
        types:
          Blunt: 1

- type: startingGear
  id: PrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetGrey
    id: PrisonerIDCard
