using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._BRatbite.TrackingHud;
using Content.Shared._BRatbite.TrackingHud.MarkerMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._BRatbite.TrackingHud.MarkerMonitor;

[GenerateTypedNameReferences]
public sealed partial class MarkerMonitorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly SpriteSystem _spriteSystem;
    private readonly SharedTransformSystem _transformSystem;
    private EntityUid? _mapUid;
    public event Action<Vector2, ProtoId<MarkerPrototype>, Color>? ClickedOnMapAction;
    private readonly static Color[] _availableColors = new Color[] {
        Color.Red,
        Color.Blue,
        Color.Orange,
        Color.Purple,
        Color.Green,
    };
    private Color? _selectedColor;
    private ProtoId<MarkerPrototype>? _selectedMarker;
    public MarkerMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entManager.System<SpriteSystem>();
        _transformSystem = _entManager.System<TransformSystem>();

        NavMap.ClickedOnMapAction += OnClickedOnMap;
        MarkerGrid.Columns = _availableColors.Length;
        PopulateMarkers();
    }

    public void SetMap(EntityUid? mapUid)
    {
        if (_entManager.TryGetComponent<TransformComponent>(mapUid, out var xform))
        {
            NavMap.MapUid = xform.GridUid;
            _mapUid = xform.GridUid;
        }
        else
        {
            NavMap.Visible = false;
        }
        NavMap.ForceNavMapUpdate();
    }

    private void OnClickedOnMap(Vector2 worldPosition)
    {
        if (_selectedColor is null || _selectedMarker is null) return;
        ClickedOnMapAction?.Invoke(worldPosition, _selectedMarker.Value, _selectedColor.Value);
        _selectedMarker = null;
        _selectedColor = null;
        PopulateMarkers();
    }

    private void PopulateMarkers()
    {
        MarkerGrid.RemoveAllChildren();
        foreach (var marker in _proto.GetInstances<MarkerPrototype>().Values)
        {
            if (marker.HideFromMonitor) continue;
            var texture = _spriteSystem.Frame0(marker.Icon);
            foreach (var color in _availableColors)
            {
                var textureButton = new TextureButton()
                {
                    TextureNormal = texture,
                    Modulate = color,
                    Scale = new Vector2(2, 2),
                    ToggleMode = true,
                };

                textureButton.OnPressed += (_) =>
                {
                    _selectedMarker = marker.ID;
                    _selectedColor = color;
                    PopulateMarkers();
                };
                if (_selectedColor == color && _selectedMarker == marker)
                {
                    var panelContainer = new PanelContainer()
                    {
                        PanelOverride = new StyleBoxFlat()
                        {
                            BackgroundColor = Color.FromHex("#464966"),
                        },
                        Children =
                        {
                            textureButton,
                        },
                    };
                    MarkerGrid.AddChild(panelContainer);
                }
                else
                {
                    MarkerGrid.AddChild(textureButton);
                }
            }
        }
    }
    public void UpdateMarkers(IEnumerable<TrackingTarget> targets)
    {
        if (_mapUid is not { } mapUid) return;
        NavMap.TrackedEntities.Clear();
        var dummy = NetEntity.ClientEntity;
        foreach (var target in targets)
        {
            var coords = _transformSystem.ToCoordinates(mapUid, new (target.TargetLocation, target.MapId));
            if (!_proto.TryIndex(target.MarkerPrototype, out var markerProto)) continue;
            var texture = _spriteSystem.Frame0(markerProto.Icon);
            // There is no reason for tracked entities to actually take entities,
            // So we just generate some dummy NetEntities
            // Unfortunately TrackedCoordinates doesn't allow you to use custom
            // NavMapBlips
            NavMap.TrackedEntities.Add(new(dummy++), new ()
            {
                Texture = texture,
                Color = target.PinColor.WithAlpha(0.90f),
                Coordinates = coords,
                Blinks = false,
                Scale = 3,
                Selectable = false,
            });
        }
    }
}
