using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BRatbite.Access;

[GenerateTypedNameReferences]
public sealed partial class LockMenu : DefaultWindow
{
    private string Password = "";
    public event Action<string>? OnEnterButtonPressed;
    public LockMenu()
    {
        RobustXamlLoader.Load(this);
        FillKeypadGrid();
    }

    private void FillKeypadGrid()
    {
        // add 3 rows of keypad buttons (1-9)
        for (var i = 1; i <= 9; i++)
        {
            AddKeypadButton(i);
        }

        // clear button
        var clearBtn = new Button()
        {
            Text = "C"
        };
        clearBtn.OnPressed += _ => Password = "";
        KeypadGrid.AddChild(clearBtn);

        // zero button
        AddKeypadButton(0);

        // enter button
        var enterBtn = new Button()
        {
            Text = "E"
        };
        enterBtn.OnPressed += _ => OnEnterButtonPressed?.Invoke(Password);
        KeypadGrid.AddChild(enterBtn);
    }

    private void AddKeypadButton(int i)
    {
        var btn = new Button()
        {
            Text = i.ToString()
        };

        btn.OnPressed += _ => Password += i.ToString();
        KeypadGrid.AddChild(btn);
    }
}
